@startuml

title __VISITOR's Class Diagram__\n

  namespace org.example {
    namespace behavioral.visitor {
      class org.example.behavioral.visitor.BlackCreditCardVisitor {
          + flightOffer()
          + gasolineOffer()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.visitor {
      class org.example.behavioral.visitor.ClassicCreditCardVisitor {
          + flightOffer()
          + gasolineOffer()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.visitor {
      interface org.example.behavioral.visitor.CreditCardVisitor {
          {abstract} + flightOffer()
          {abstract} + gasolineOffer()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.visitor {
      interface org.example.behavioral.visitor.ElementOffer {
          {abstract} + accept()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.visitor {
      class org.example.behavioral.visitor.FlightOffer {
          + accept()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.visitor {
      class org.example.behavioral.visitor.GasolineOffer {
          + accept()
      }
    }
  }
  

  org.example.behavioral.visitor.BlackCreditCardVisitor .up.|> org.example.behavioral.visitor.CreditCardVisitor
  org.example.behavioral.visitor.ClassicCreditCardVisitor .up.|> org.example.behavioral.visitor.CreditCardVisitor
  org.example.behavioral.visitor.FlightOffer .up.|> org.example.behavioral.visitor.ElementOffer
  org.example.behavioral.visitor.GasolineOffer .up.|> org.example.behavioral.visitor.ElementOffer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
