@startuml

title __CARDS's Class Diagram__\n

  namespace org.example {
    namespace creational.abstractfactory {
      namespace cards {
        interface org.example.creational.abstractfactory.cards.Card {
            {abstract} + getCardNumber()
            {abstract} + getCardType()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace cards {
        class org.example.creational.abstractfactory.cards.CardFactory {
            + create()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace cards {
        enum CardType {
          MASTERCARD
          VISA
          value
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace cards {
        class org.example.creational.abstractfactory.cards.MasterCard {
            + getCardNumber()
            + getCardType()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace cards {
        class org.example.creational.abstractfactory.cards.Visa {
            + getCardNumber()
            + getCardType()
        }
      }
    }
  }
  

  org.example.creational.abstractfactory.cards.CardFactory .up.|> org.example.creational.abstractfactory.AbstractFactory
  org.example.creational.abstractfactory.cards.MasterCard .up.|> org.example.creational.abstractfactory.cards.Card
  org.example.creational.abstractfactory.cards.Visa .up.|> org.example.creational.abstractfactory.cards.Card


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
