@startuml

title __COMPOSITE's Class Diagram__\n

  namespace org.example {
    namespace structural.composite {
      interface org.example.structural.composite.AccountComponent {
          {abstract} + getAmount()
          {abstract} + showAccountName()
      }
    }
  }
  

  namespace org.example {
    namespace structural.composite {
      class org.example.structural.composite.AccountComposite {
          - childAccounts : List<AccountComponent>
          + AccountComposite()
          + addAccount()
          + getAmount()
          + removeAccount()
          + showAccountName()
      }
    }
  }
  

  namespace org.example {
    namespace structural.composite {
      class org.example.structural.composite.CurrentAccount {
          - amount : Double
          - name : String
          + CurrentAccount()
          + getAmount()
          + showAccountName()
      }
    }
  }
  

  namespace org.example {
    namespace structural.composite {
      class org.example.structural.composite.SavingsAccount {
          - amount : Double
          - name : String
          + SavingsAccount()
          + getAmount()
          + showAccountName()
      }
    }
  }
  

  org.example.structural.composite.AccountComposite .up.|> org.example.structural.composite.AccountComponent
  org.example.structural.composite.CurrentAccount .up.|> org.example.structural.composite.AccountComponent
  org.example.structural.composite.SavingsAccount .up.|> org.example.structural.composite.AccountComponent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
