@startuml

title __METHODS's Class Diagram__\n

  namespace org.example {
    namespace creational.abstractfactory {
      namespace methods {
        class org.example.creational.abstractfactory.methods.Credit {
            + doPayment()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace methods {
        class org.example.creational.abstractfactory.methods.Debit {
            + doPayment()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace methods {
        interface org.example.creational.abstractfactory.methods.Method {
            {abstract} + doPayment()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace methods {
        class org.example.creational.abstractfactory.methods.MethodFactory {
            + create()
        }
      }
    }
  }
  

  namespace org.example {
    namespace creational.abstractfactory {
      namespace methods {
        enum MethodType {
          CREDIT
          DEBIT
          value
        }
      }
    }
  }
  

  org.example.creational.abstractfactory.methods.Credit .up.|> org.example.creational.abstractfactory.methods.Method
  org.example.creational.abstractfactory.methods.Debit .up.|> org.example.creational.abstractfactory.methods.Method
  org.example.creational.abstractfactory.methods.MethodFactory .up.|> org.example.creational.abstractfactory.AbstractFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
