@startuml

title __INTERPRETER's Class Diagram__\n

  namespace org.example {
    namespace behavioral.interpreter {
      class org.example.behavioral.interpreter.AndExpression {
          + AndExpression()
          + interpret()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.interpreter {
      interface org.example.behavioral.interpreter.Expression {
          {abstract} + interpret()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.interpreter {
      class org.example.behavioral.interpreter.OrExpression {
          + OrExpression()
          + interpret()
      }
    }
  }
  

  namespace org.example {
    namespace behavioral.interpreter {
      class org.example.behavioral.interpreter.TerminalExpression {
          - text : String
          + TerminalExpression()
          + interpret()
      }
    }
  }
  

  org.example.behavioral.interpreter.AndExpression .up.|> org.example.behavioral.interpreter.Expression
  org.example.behavioral.interpreter.AndExpression o-- org.example.behavioral.interpreter.Expression : expression1
  org.example.behavioral.interpreter.AndExpression o-- org.example.behavioral.interpreter.Expression : expression2
  org.example.behavioral.interpreter.OrExpression .up.|> org.example.behavioral.interpreter.Expression
  org.example.behavioral.interpreter.OrExpression o-- org.example.behavioral.interpreter.Expression : expression1
  org.example.behavioral.interpreter.OrExpression o-- org.example.behavioral.interpreter.Expression : expression2
  org.example.behavioral.interpreter.TerminalExpression .up.|> org.example.behavioral.interpreter.Expression


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
